### ISSUE TITLE
This app should recognize the UK NHS QR code, since they are equipollenti

### ISSUE THREAD

**Issue by cloudsecurity82** [ministero-salute/it-dgc-verificaC19-android#107]
## Feature description
This app should recognize the UK NHS QR code, since they are equipollenti

## Problem and motivation
Italian expats that vaccinated in UK, returning to Italy for summer vacation,  cannot get a coffee or go to the restaurant

I can't do anything without this
## Is this something you're interested in working on
No

**Comment by astagi** [comment]
Hi @cloudsecurity82 we're working to make the app recognizing UK certificates, stay tuned!

**Comment by cloudsecurity82** [comment]
Amazing!! Thanks!

**Comment by cesaregardito** [comment]
@cloudsecurity82  fantastic news that it will soon be compatible with QR Codes, but _as written_ the "equipollenza" circular letter does not say that you need to use the app to verify an "equipollente" foreign pass. For instance, US ones just don't have a QR Code, so you'll never be able to use the app to certify their validity.

So, while we wait for the app to be updated... the pass is already valid and you can use it to do anything that an Italian person could do with their green pass (except border controls), and when you show the NHS Covid Pass you should not make them scan the QR. Even better, _print it_ without the QR. I am using the NHS letter.

Least but not last, it is also possible (but not mandatory) to pop to your local ASL and convert your UK pass in an EU pass. Depending on the location, it can vary from very easy (just send an email) to very hard (book an appointment in a faraway office).

**Comment by axjslack** [comment]
@cesaregardito Although is it true that VerificaC19 has not the purpose to verify other type of codes (for non-EU countries or not Green Pass like) is anyway true that not all the employees in bar, restaurant, cinemas, theaters are aware of this circular letter. Many workers and local's owners will consider the output of VerificaC19 as the only way to regulate the access. If you think about it, this app is born to make easier the life of local's owners and employees and guarantee easily access to people in proper right.  As the mentioned circular allow to UK double vaccinated people the same rights to full Green Pass owners ("equipollenza" is equivalence), and considering that NHS covid pass already uses a QR-code, makes the application work with these seems pretty logical and fair, not only for UK tourists, but for Italian living in UK as well. Otherwise this could start endless problem between NHS covidpass customer and restaurant manager, with the customer that for every restaurant have to explain this not so known circular to every manager, hoping that is believed.  Also, considering that people that are coming in the UK are already subject to a 5 days quarantine, a 6th day test to come out from quarantine, sound pretty cruel adding a 7th day spent in a ASL, without a fixed procedure, with every ASL that are doing in their own way, with possible and likely queue. Some ASL contacted weren't fully aware of the conversion problem. If the procedure of conversion could have been made online and automatically I would say "go for it", but this is far from the current reality.

**Comment by cesaregardito** [comment]
@axjslack I am aware - the advice I give to people in my expats community is to bring the version without a QR Code of the NHS Vaccination Certificate. Indeed, if your certificate has a QR, a misunderstanding is essentially guaranteed.

Hopefully it is easy enough that it can be implemented very soon!

**Comment by twillia2** [comment]
It is already fixed in https://github.com/ministero-salute/it-dgc-verificaC19-android/commit/e2f6e3fba53747b053778b2418ef6a871d52b3d1


no?

**Comment by astagi** [comment]
@twillia2 yes, it's already fixed, but we're waiting to have UK public keys on our server. I'll notify you when this happens.

**Comment by twillia2** [comment]
> @twillia2 yes, it's already fixed, but we're waiting to have UK public keys on our server. I'll notify you when this happens.

Do you have a ETA please?

**Comment by axjslack** [comment]
@twillia2 Seems that the patch made it (merged) on the 1.1.0 ver (571). 

@astagi It will work on the 1.1.0 or it will require a new release? Out of curiosity I tested the 1.1.0 on my certificate and doesn't work, but I assume this is currently normal.  I would like to thank you for your answers and for being so open about information.

**Comment by cesaregardito** [comment]
@axjslack I did notice a difference between 1.1.0 and the previous versions: it used to say "Firma non valida". Now it does pick up my name and date of birth, but then it still says "Certificazione non valida" (this must be due to UK public keys not being in the server).

**Comment by axjslack** [comment]
@cesaregardito 
I saw that the app try to update some information, possibility keys as well once started. On this consideration, makes sense that pub keys are stored on server.

I'm getting a different error on mine "Errore di lettura del QR code oppure non è il certificato verde", but it's likely that I'm doing something wrong, but I could not tell what. (I'm trying to scan the PDF generated by the NHS app, the one with 2 qr codes, scanning the one of the second dose)

**Comment by cesaregardito** [comment]
@axjslack Yes every time you start the app it updates the database, if it can. 

About your problem... well, if you have the latest release, the plot thickens. I tried to scan the second-dose QR Code from my NHS Covid Pass, and it picks up my name and date of birth. Is your QR code up-to-date? UK Codes expire after 30 days for some reason.

**Comment by twillia2** [comment]
@cesaregardito 
> About your problem... well, if you have the latest release, the plot thickens. I tried to scan the second-dose QR Code from my NHS Covid Pass, and it picks up my name and date of birth. Is your QR code up-to-date? UK Codes expire after 30 days for some reason.

it’s as @astagi says above. The apps themselves can now recognise UK codes (even the old version got my name and DOB) but the servers have not yet got the UK keys to validate them, so the apps still believe they are invalid.

**Comment by cesaregardito** [comment]
That's how it should be atm, so no more apk updates necessary... but then
the other user said that their app doesn't pick up their name and DOB.

**Comment by twillia2** [comment]
> That's how it should be atm, so no more apk updates necessary... but then the other user said that their app doesn't pick up their name and DOB.

Maybe they are using the wrong QR code? 

We have 2 types in the UK- a domestic code (which Verifica19 really does not like) and the international codes (you have 2 if you’ve had both jabs) which Verifica should at least recognise a name and DOB from.

**Comment by cesaregardito** [comment]
Yes - I am curious about what that user reports. I also wonder if there
will be issues for the people vaccinated with "Covishield", it was a pretty
major story a few weeks ago (it is the Vaxzevria vaccine but with the
indian label, so not formally recognized by EMA).

**Comment by axjslack** [comment]
I really don't know. It's a PDF I have generated with the NHS App. It has 2 QR codes (one for each dose) and I tried to scan the one of the second dose.  It will expire in 3 days. It may be a different type of certificate, or could be the phone I use to scan (an old Huawei with Android 8), or may be the screen of the phone with the certificate (newer phone). In all of this, this functionality is still not ready.

**Comment by axjslack** [comment]
![Uploading PXL_20210811_160409928.jpg…]()

**Comment by axjslack** [comment]
![PXL_20210811_160409928](https://user-images.githubusercontent.com/1014267/129075830-024c0e4a-3cb5-4fc5-85ef-be17e7fe5ffd.jpg)

**Comment by astagi** [comment]
@axjslack @cesaregardito @twillia2 @cloudsecurity82 the app is now able to recognize UK certificates 🎉 Could you please test this feature? You don't need to update the app, just be sure that you have VerificaC19 1.1.0 installed (kill and reopen it to force keys update if needed).

**Comment by axjslack** [comment]
@astagi 
Looks like working. 
With the old pdf there wasn't a way to make it work. I tried also to switch phone (the Huawei with the PDF and Pixel2 with the VerificaC19 App), but didn't work. 

The I went to NHS App and I generate again a new travel certificate and it has worked. 
Screen is green with the green tick and said:
"Certificazione valida in Italia ed in Europa" and the my data. I don't publish the photo because contains some personal data (Full name and date of birth). 

So, good job. You made my life (and the one of UK vaccinated people) much more easier. Thank you a lot. 
When I will come to Italy I own you a beer.

**Comment by twillia2** [comment]
> @axjslack @cesaregardito @twillia2 @cloudsecurity82 the app is now able to recognize UK certificates 🎉 Could you please test this feature? You don't need to update the app, just be sure that you have VerificaC19 1.1.0 installed (kill and reopen it to force keys update if needed).

Grazie! Tested with mine and my partner’s NHS codes and both now show as valid. Thank you all for your work.

**Comment by astagi** [comment]
Thank you everyone for having tested the app. I'll close the issue!

@axjslack I've never refused a beer 🍻

@cesaregardito sure, you can suggest an alternative text in a new issue!

**Comment by erenato** [comment]
Hi guys, thanks for working to fix the UK code problem. One issue I am having is that Northern Ireland-issued codes are still not valid, but England and Wales are working. Not sure if the NI code has diff keys

**Comment by cloudsecurity82** [comment]
Mmmm, maybe it's just me, but I updated both Android/Apple VerificaC19, I
generated a new UK NHS QR Code, and it still doesn't validate it correctly.
It recognize my name and date of birth, but still no luck in getting the
green light :(
I shall wait few more days, maybe the backend update of the keys hasn't
been done yet?

**Comment by astagi** [comment]
@erenato team is working on it! I see you opened a different issue, that's great!

@cloudsecurity82 do you have only the 1st dose?

**Comment by cloudsecurity82** [comment]
I had both, and it's been more than a month now since my second Moderna
dose...
I'm scanning the 2nd dose QR code of course, but still not luck...

**Comment by astagi** [comment]
Uhm really weird @cloudsecurity82 could you please raise a new issue for this? I'll notify the team, I'm on vacation right now! Thanks for testing thoug!

**Comment by cloudsecurity82** [comment]
I tried on few devices and it works now!
