### ISSUE TITLE
Commit 8665458 introduce a violation of GPDP requirements

### ISSUE THREAD

**Issue by studiofuga** [ministero-salute/it-dgc-verificaC19-android#110]
## Describe the bug

As from GPDP requirements, verifiers should NOT be able to have any information about the type of vaccination or health state of the verified user.

With commit 8665458 a few icons are shown depending from the state of the vaccinations. This is agains the GPDP recommendations.

## Expected behaviour

When a partially valid certificate is scanned (that is: 1 dose out of 2 and current time is inside the validity window), GREEN checkmark should be displayed. When the validity window is NOT yet started (i.e. current time is before starting time) RED cross should be displayed.

## Current behaviour

When a partially valid certificate is scanned (that is: 1 dose out of 2 and current time is inside the validity window), BLUE checkmark is displayed. When the validity window is NOT yet started (i.e. current time is before starting time) BLUE mark is displayed.

**Comment by Aldo97** [comment]
To solve this problem it is possible to introduce a switch in the UI that allows the operator to switch between a "european" check and a "national" check.
In this way if the operator sets the operative mode as "national" he would see the certificate valid (green) also in case of a partial vaccination, if the operator sets the operative mode as "european" he would see the same certificate as not valid (with the red cross).
In both in case of a certificate not yet valid the result must be a red cross without any information about the future validity of the certificate.

Summarizing:
"National":
1 dose(after 2 weeks), 2 doses, test, recovery = valid
1 dose(before 2 weeks) and current not valid certificates = not valid
"European":
2 doses, test, recovery = valid
1 dose and current not valid certificates = not valid

This is only a suggestion, but it seems to me the best solution (otherwise we may need to build two twin apps)
