### ISSUE TITLE
Scan works only first time in Raspberry Pi 3-4

### ISSUE THREAD

**Issue by davnec** [ministero-salute/it-dgc-verificaC19-android#154]
## Describe the bug

I've installed the app on raspberry pi 4 with Lineage 18 (Android 11) and pi 3 (lineage 17,android 10) but I have an issue scanning the code; first time the verification works, but the following ones don't. I have to restart all the sistem to make works again (but only the first time)
The app start the camera, I can see the target box, the red line, but the qr code is not recognize (i don't see the orange dot).
I tryed the app from the store and compiling the source.

## Steps to reproduce the issue

1. Open the app
2. Scan the first code
3. Scan completed successfully
4. scan next pass
5. app show camera, with target box, i see the pass captured by the camera, but the app ignore the code 

## Technical details

- Raspberry Pi 4
- Rapsberry Pi 3
- Lineage 18 (Android 11)
- Lineage 17 (Android 10)

**Comment by rawmain** [comment]
Hello @davnec

Lineage-rpi had anyway known issues with some apps that required camera usage. You should lookup indeed from adb logcat for Zxing <-> Camera management errors while you're performing the 2nd QR scan attempt.

Besides, you can also check the situation - _further QR scans together with logcat checks_ - by using a release-build with different version dependencies for Zxing core libraries.

You can use for instance this [custom release-build](https://github.com/VC19tests/verificaC19-android-lower-minSDK/releases/tag/develop-1.1.2-SDK-API23-20211013), that relies on current develop branch code + official IT DGC-SDK integration. 

It uses indeed different Zxing settings than the official releases, since its Zxing dependencies have been downgraded in order to allow OK also with minSDK API23 targets (Android Marshmallow 6.0).

**Comment by Giuseppe-1977** [comment]
I woud like to install Android on rasberry. How did you get in order to test all this?

**Comment by davnec** [comment]
Thanks, for now I'm using another version of hardware with different android version and works! 
I've noticed that the reading speed with androi version si very slow compared with iOS version, bui i think that is related to qrcode library performance, but I think that there is no solution for now...

@Giuseppe-1977 sorry for the delay... I used the LineageOS 18.1 for Raspberry PI

**Comment by luancarli-kronotech** [comment]
I used Emteria distro to create a kiosk device, I noticed the same behaviour with a camera, but to have a better QR reading I used a USB external professional reader. With this device there are no issues.
