### ISSUE TITLE
GC expiry calculation is based on unauthenticated current OS datetime

### ISSUE THREAD

**Issue by popolla** [ministero-salute/it-dgc-verificaC19-android#168]
I've always assumed that the GC expiry date computation was based on an authenticated current time from the server.
Today I set the datetime of my smartphone to a date in the past, and the application shows an expired GP to be valid.
Is this behavior considered secure enough?

**Comment by rawmain** [comment]
Hello @popolla 

> I've always assumed that the GC expiry date computation was based on an authenticated current time from the server.

The dgca-verifier-app must work in full airplane/offline mode too = it has to rely on device-time check for offline certificate verification - according to [DGC Technical Specifications / Guidelines for verifier-apps](https://ec.europa.eu/health/sites/health/files/ehealth/docs/digital-green-certificates_v4_en.pdf).

According to such specifications, the verifier-apps aren't allowed to use the Internet connection in order to carry out the verifications, but only for app data + national/business rules updates (_required only on first app-run - then suggested every 24 hours_).

NTP connections are allowed by the guidelines. However, timestamp comparison with responses from trusted NTP servers couldn't be enough w/o an active internet connection during all verifications. 

Therefore, app's datetime checks should rely also on GPS and/or GSM time synchronization checks - in order to fully minimize the risk of time-mismatches during the scans.

"_The game is not worth the candle_" : 

- Such additional app-permissions (location for GPS and/or phone for GSM - mobile network), would require anyway new DPIA + ITA DPA (GPDP) checks = it's not just a matter of merging new code.

- Further datetime-sync checks don't bring any improvement in the threat model = cheating verifiers wouldn't care at all.

-------------------

You may check the closed issue #88 & its (long) conversation-thread for further details.

**Comment by popolla** [comment]
You can change this to enhancement request, but it's debatable. The specs don't really "suggest" daily updates of app data/rules, they say daily updates are "sufficient", meaning that the app should be unusable if data/rules are not updated for more than 24 hours (I assume such a check exists in the code). The specs state that the verification process by national rules must be performed device-side, they really don't prevent the current time (which is fundamental for the verification) to be fetched from the internet.
I highly doubt that none of the responses to the (at least daily) update requests could contain a trusted timestamp already, and I don't see the difficulty in using such a timestamp to validate a plausible device time in the 24 hours period, for example. NTP is overkill, we really want to prevent misuse here, interaction with the servers uses TLS so we are good to go.

The whole thing is based upon visual feedbacks and users tend to focus on the red/green background color and the big check mark/cross sign. A malicious/accomplice verifier with no cross-examination could indeed create problems, and saying this is rare/unimportant/convoluted/unnecessary in the current national situation is far from reality, specs and security common practice. The game isn't that hard and does worth the candle.

**Comment by rawmain** [comment]
Hello @popolla 

> You can change this to enhancement request, but it's debatable.
[...]
> The game isn't that hard and does worth the candle.

I've just opened the [Feature-Request issue 38 in the DGC-SDK repo](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/38) with a raw implementation-draft for app + dgc-sdk, in order to allow the official team to (re)evaluate the addition of serverTime sync checks.

Such changes can't bring obviously any improvement in the threat model (_cheating verifiers don't care..._), but may help anyway  fair verifiers to intercept wrong devicetime settings (i.e. after DST->ST switch).

**Comment by popolla** [comment]
Hello @rawmain, first of all thank you for being professional on this topic. I'm closing the issue because your feature request is well formulated and effective to me.

Let me just say, with most seriousness and respect, that I've read some arguments around the threat model, praised by many within previous issues, that seem somewhat biased/simplistic and do not actually hold up in real case scenarios, nor remotely take into account the present social context with appropriate concern. This is not the same as privately validating a website TLS certificate, there are people involved, acting on the basis of a visual feedback.

_Cheating verifiers don't care..._ When did that become a technical argument? How is it supposed to fit the specific context? The fact that a verifier could "cheat" in a million other ways is no justification for leaving the possibility to easily produce a GUI response that could be used to mislead - and I can think of quite a few real world examples for both false validity and false invalidity. Moreover, since when are we engineers supposed to measure the intentions of misuse?

In the end, this actually goes beyond threat models: the main function of the app is validating a DGC by the national rules. I do not read "validating DGC by national rules, unless the date of the device gets changed". We should not abstract from problems by saying that the app must be able to work offline for 24 hours, it just doesn't make sense. Thanks again for your attention.
