### ISSUE TITLE
Is the key revocation list working?

### ISSUE THREAD

**Issue by djechelon** [ministero-salute/it-dgc-verificaC19-android#180]
This is a spin-off of #103

Here, I don't want to debate on the revocation on individual DGCs, but discuss something odd happened after the leak of blatantly fake DGCs (Hitler, Mickey Mouse...).

I was following the updates on [Paolo Attivissimo's blog](https://attivissimo.blogspot.com/2021/10/perche-questi-codici-qr-sembrano-green.html)

## Describe the bug

On October 27th, alleged Hitler certificates were considered invalid (the key was likely revoked) on my device. I can still see on Attivissimo's blog that Hiter's certificate was invalid

![immagine](https://user-images.githubusercontent.com/3042285/139219579-42d08e32-6dee-49ce-b099-cb369406910f.png)

On October 28th, the certificates posted on the blog **AND** on [#103 by user jumpjack](https://github.com/ministero-salute/it-dgc-verificaC19-android/issues/103#issuecomment-953601295) are considered valid

Example certificate (invalid for Paolo Attivissimo, valid for me)

![immagine](https://user-images.githubusercontent.com/3042285/139221551-d5de3eb0-19a8-4f26-bacc-9ffa264f2cab.png)

## Expected behaviour

Once the revocation list has been updated with revoked keys, certificates issued with those keys must be invalid **forever**

## Steps to reproduce the issue

As described, this is a time-related issue. Initially, the certificates were considered valid, but at least once in October 27th they were considered revoked.

## Additional context

All DGC material (alleged QR codes) available at the Attivissimo blog I cited.

I deleted all app data and waited for it to update the revocation list.

Yet again, this issue does **not** discuss revoking individual fake certificates like #103, but only mass revocation of certificates allegedly issued with the same private key.

**Comment by Valeri0p** [comment]
The issue is of extreme importance, but while no official statement has been made, evidence suggests this is more probably a case of API abuse rather than a leak of the private key(s).
Some references:
https://github.com/ehn-dcc-development/hcert-spec/issues/103
https://github.com/denysvitali/covid-cert-analysis

Also it's interesting to note how other[ European countries have systems capable of revoking each certificate individually.](https://twitter.com/TousAntiCovid/status/1441319032355840001)

**Comment by djechelon** [comment]
But even if it's not a leak, why would some DGCs invalid _yesterday_ become valid _today_? That is the scope of the issue. Once a single pass or a whole key is revoked, it should be permanent

**Comment by jumpjack** [comment]
> But even if it's not a leak, why would some DGCs invalid _yesterday_ become valid _today_? That is the scope of the issue. Once a single pass or a whole key is revoked, it should be permanent

Because the system manager was probably playing with enabling/disabling the private key used to generate the fake codes, and discovered that if he disable the key, some millions of valid greenpass are disabled too, so it enabled it back

**Comment by MollerAndre** [comment]
What happened revealed one of the weak points of the whole DCC thing. If one (ore more) DSC are compromised then there's no way to tell if a signed certificate is genuine or not (unless you verify it directly with the issuer) until the compromised key is revealed to the public. But how many other compromised keys are there on the dark web used by someone to produce fake but still valid certificates? We do not know.

However there are a few things we can do to improve reliability of apps like VerificaC19. One thing should by to compare the key IDs with their respective emitting countries (which are known). If i.e. a certificate of an italian citizen signed (according to the data in the code) by the official italian issuer is signed with the french key obviously is a fake.

The app, also, should show the country of the signing key so that a verifier can easily report to authorities those people who are from one nation but have certificates signed by another nation (of course all possible exceptions must be taken in account).

Just my two cents...

**Comment by frankwalter1301** [comment]
Better leave this security vulnerability as it is because this green pass thing hurts human rights IMHO.

Just my two cents...

**Comment by jumpjack** [comment]
Fortunately the names of all persons refusing vaccine are recorded for posterity. It will matter.

**Comment by djechelon** [comment]
> The app, also, should show the country of the signing key so that a verifier can easily report to authorities those people who are from one nation but have certificates signed by another nation (of course all possible exceptions must be taken in account).

@MollerAndre I disagree with the above statement. There are so many _individual_ cases (e.g. a semi-permanent resident working abroad, people who traveled to get vaccinated in advance*) that trying to match the country of citizenship with the country of issuance of the DGC would reveal far too many false positives.

*Take Serbia as an intuitive example. While not EU country, there was a time a number of people used to fly to Belgrade just to get the injection 💉


@all others, please remain in topic. The topic is: a certificate was first revoked, then re-admitted to validity.

**Comment by MollerAndre** [comment]
> @MollerAndre I disagree with the above statement. There are so many _individual_ cases (e.g. a semi-permanent resident working abroad, people who traveled to get vaccinated in advance*) that trying to match the country of citizenship with the country of issuance of the DGC would reveal far too many false positives.

That's why I wrote that there are exceptions to take into account but consider, for example, italian citizens. If one of them shows a valid certificate signed with the key of Poland, France or another country it's just a bit suspect but still possible... if many of them star showing certificates from the same country that could only mean that there is a flaw in the system.

**Comment by Valeri0p** [comment]
I agree with @MollerAndre , since as far as we know the Italian servers have not been compromised till now and most of the vulnerable servers seem to be those of extra-EU countries (eg. Macedonia, Vietnam, etc...), I think it would be a very effective way to expose forged certificates regarding Italian citizens; it would be a little harder to tell for tourists and anyone that travels frequently for any reason, but I don't think the number of false positives would be excessive.

**Comment by frankwalter1301** [comment]
I don't know where you got those informations, but compromised servers are
from Italy, Germany and other countries too that I forgot to mention. So this is another motivation to not follow this way, other than the human rights thing, of course.

Il sab 30 ott 2021, 20:09 Valeri0p ***@***.***> ha scritto:

**Comment by MollerAndre** [comment]
> I don't know where you got those informations, but compromised servers are from Italy, Germany and other countries too that I forgot to mention. So this is another motivation to not follow this way, other than the human rights thing, of course. Il sab 30 ott 2021, 20:09 Valeri0p ***@***.***> ha scritto:

So far there's no proof of fake certificates signed with the Italian key, do you have one?
The only keys I know of are from Poland and France.

**Comment by frankwalter1301** [comment]
> > I don't know where you got those informations, but compromised servers are from Italy, Germany and other countries too that I forgot to mention. So this is another motivation to not follow this way, other than the human rights thing, of course. Il sab 30 ott 2021, 20:09 Valeri0p _**@**_.***> ha scritto:
> 
> So far there's no proof of fake certificates signed with the Italian key, do you have one? The only keys I know of are from Poland and France.

Hi. I saw a certificate with the name of "UBISOFT MERDA" and another one with "NEGRO" and something else. I remember those being italian. Btw at the moment I don't have the QR code, but I asked my friend to provide it to me. So I will give you the QRs tomorrow hopefully.

**Comment by MollerAndre** [comment]
> Hi. I saw a certificate with the name of "UBISOFT MERDA" and another one with "NEGRO" and something else. I remember those being italian. Btw at the moment I don't have the QR code, but I asked my friend to provide it to me. So I will give you the QRs tomorrow hopefully.

A certificate with Italian silly names doesn't necessary mean it was signed with the Italian private key. If you can find and attach those QR codes in this thread they can be analysed.
