### ISSUE TITLE
Third vaccination flagged as invalid

### ISSUE THREAD

**Issue by bedo2991** [ministero-salute/it-dgc-verificaC19-android#188]
## Describe the bug
I have 2 QR codes for a third vaccine that are currently shown as invalid by the app.

Vaccine 3/**2** - 15/10/2021 - QR Generated in Italy => Invalid
Vaccine 3/3 - 03/11/2021 - QR Generated in Germany => Invalid

## Expected behaviour
These codes (or at least the first one, if 14 days after the vaccination should pass) should be valid. The German app (CovPass Check) validates both of them.

## Steps to reproduce the issue
Scan a code for a third vaccination

## Technical details

- Pixel 4a, Android 12

## Possible Fix
Update the validation rules for the third vaccination

**Comment by MollerAndre** [comment]
Third dose (or the second one for those people vaccinated with J&J) is a booster and is considered valid from the same day of the vaccination, so DCC reporting this "extra" dose should be considered valid since the day they are issued. If Covid19 app doesn't recognise it as valid is a serious bug that should be fixed as soon as possible since in the next weeks/months more and more of such perfectly valid certificates will be issued in Italy and in Europe.

It's also misleading that such certificates issued by Italy report it as third dose of two doses... it should be third dose of three just like the German one.

**Comment by bedo2991** [comment]
Non che a nessuno sembra sia fregato qualcosa, ma a quanto pare è un problema di Cache.
**Eliminando tutti i dati dell'app, poi il vaccino viene mostrato come valido.**
Questo sembra succedere su diversi dispositivi android (testato su 4 diversi dispositivi, anche di amici e 3 volte su 4 non ha funzionato). Con la versione per iOS nessun problema.
