### ISSUE TITLE
Tag 1.1.7 release

### ISSUE THREAD

**Issue by ilGimmy** [ministero-salute/it-dgc-verificaC19-android#201]
## Your Question

On Play Store release 1.1.7 is available, however this is not tagged on this repo.

Can you tag 1.1.7 properly?

Regards
Andrea

**Comment by rawmain** [comment]
Hello @ilGimmy 

> On Play Store release 1.1.7 is available, however this is not tagged on this repo.

There is no 1.1.7 tag for app/UI source code because there is no diff with 1.1.6 tag code.

VerificaC19 releases 1.1.6 & 1.1.7 for Android share indeed the same code for : 

- **App/UI** ([release/1.1.6](https://github.com/ministero-salute/it-dgc-verificaC19-android/tree/release/1.1.6)) -> just align versionCode/versionName references in app\build.gradle (584/1.1.6 -> 585/1.1.7) in case you also need/want to perform Reproducible-Builds against the prodrelease packages available from Google Play Store / Huawei AppGallery.

- **DGC-SDK** ([release/1.0.2](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/release/1.0.2))

Such releases differ only in the **EU DCC Core Decoder** ([main](https://github.com/eu-digital-green-certificates/dgca-app-core-android)) module code = 1.1.7 uses indeed the same EU DCC code used by 1.1.6 (_updated until SEP 28_) + 1 [additional commit](https://github.com/eu-digital-green-certificates/dgca-app-core-android/commit/8c2872b77efb98c61c4f13fb5bdc6a1edff99716) for EU DCC Decoder - in order to fix a minor Base45 decoding bug in the EU DCC decoder.
