### ISSUE TITLE
Greenpass type selected but not active at first run

### ISSUE THREAD

**Issue by jumpjack** [ministero-salute/it-dgc-verificaC19-android#213]
At first run of version 1.1.8, first one distinguishing "standard" from "super" greenpass, the "standard" greenpass type is already selected, but app complains about no type selected, so the user must access the selection screen, which shows the standard greenpass already selected by default.

**Comment by rawmain** [comment]
Hello @jumpjack 

> At first run of version 1.1.8, first one distinguishing "standard" from "super" greenpass, the "standard" greenpass type is already selected, but app complains about no type selected, so the user must access the selection screen, which shows the standard greenpass already selected by default.

That's not a bug, but instead the right behaviour since - _after new installation or app-update from previously installed releases_ - the scan mode hasn't been manually chosen by the operator.

Therefore, until the operator performs the initial mode selection (_keeping 3G Base mode by tapping on it for confirmation or switching to 2G Rafforzata mode_), the verifier-app prevents scanning.

**Comment by jumpjack** [comment]
Ok but the radiobox is already pre-selected by the app; it's a GUI bug, not an algorithm bug.
