### ISSUE TITLE
Leverage OpenVerify for scanning Canadian SMART health QR codes (and some US states)

### ISSUE THREAD

**Issue by a-irvine** [ministero-salute/it-dgc-verificaC19-android#245]
## Expected Benefits
I believe this would help facilitate easier access for people coming from Canada/US into the many venues that require the Green Pass / Super Green Pass. I have had minimal issues presenting the Canadian credentials, but not all venues / hotels honor the certificate, despite the ordinance.
When implemented, (Similar to the NHS pull request, but perhaps more involved due to a different algorithm? https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/102)
If possible, leverage the existing code as needed in https://github.com/ongov/OpenVerify similar to the NHS code implementation.

## Problem and motivation
Currently, SMART health QR codes from Canadian provinces (and some US states that use them also) are not recognized by VerificaC19. 
This presents challenges for tourists, and foreigners in Italy as not all venues respect the ordinance of equivalence.

## Is this something you're interested in working on

Unfortunately, I do not possess the skills to implement this feature, but would be happy to test!

**Comment by rawmain** [comment]
Hello @a-irvine 

> SMART health QR codes from Canadian provinces (and some US states that use them also) are not recognized by VerificaC19.

[Smart Health Cards specs](https://spec.smarthealth.cards/) are incompatibile with [EU-DCC implementation](https://ec.europa.eu/health/ehealth-digital-health-and-care/ehealth-and-covid-19_en#eu-digital-covid-certificate) = it isn't just a matter of signature check (_NHS certificates' closed issue_), since all the rest - even the JSON payload/schema itself - is fully different.

Besides, it's anyway an out-of-scope request.

Italian DGC Validation checks through VerificaC19 & DPCM 12/10/2021 compliant apps/platforms apply indeed only to :

- **EU-DCC schema compliant DGC V/R/T certificates** = Vaccination/Recovery/Test digital certificates, that have been issued by EU countries + [33 third non-EU countries](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en#recognition-by-the-eu-of-covid-certificates-issued-by-third-non-eu-countries) (_Canada & USA States not included among them_), according to EU-DCC specs.

- **new IT-only CRT E ([Exemptions](https://github.com/ministero-salute/it-dgc-documentation/blob/master/EXEMPTIONS.md)) certificates** = Italian issued digital certificates of vaccination exemption

**Comment by a-irvine** [comment]
> 

This explains things clearly :)
Perhaps there is a way on the Canadian/US side to issue an EU-DCC schema compliant certificate in addition to the SMART certificate.
Closing this request, and thank you for the quick feedback.
