### ISSUE TITLE
Change min sdk to 23

### ISSUE THREAD

**Issue by francescogatto** [ministero-salute/it-dgc-verificaC19-android#95]
## Current Implementation

In this moment the app supports only Android versions >= 8 . 

## Suggested Enhancement

With [desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) and [downgrade](https://github.com/journeyapps/zxing-android-embedded#older-sdk-versions) of the zxing library is possible to downgrade the min sdk to 23 

## Expected Benefits
People with android version >= 6 can download the app from the store

**Comment by Enrico204** [comment]
Uhm, I think that some of the "desugaring" process was done in https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/71 , can you check? Maybe some work can be done after that PR is merged (I have an Android 6 device, I can test it).

[Note that Android below 7.1.1 will break somewhen between now and 2024 due to LE certificate expiration](https://letsencrypt.org/2020/11/06/own-two-feet.html) (let's encrypt is virtually everywhere nowadays). While I support your issue and I sincerely hope that we don't need this app in 2024, I think that it would be wise to update the phone :-)

**Comment by astagi** [comment]
@francescogatto personally I think that downgrading zxing library is not a good idea. This library is vital for VerificaC19.

Android 6.x has a market share of ~4%, while Android 7.x is around 8%. I think that supporting Android 7.x devices is enough for a verifier app and the PR mentioned by @Enrico204 could support Android 7.x without downgrading zxing core lib. What about changing the topic of this issue to "Change min SDK to 24"?

**Comment by rawmain** [comment]
Hello @astagi 

According to preliminary tests on real devices in range API23<->API30, partial Zxing downgrade isn't breaking the app's UX. 

I've submitted anyway a related PR #113 with tested commits on release 1.1.0 (versionCode 571) just to allow you to check.


By the rest, even though further minSDK downgrade to API Level 21 (Lollipop 5.0) - _minimum limit threshold according to DGC core decoder_ - is technically possible,.. I can't recommended it at all - according to tests on real devices.


Android Keystore supports indeed AES only since API Level 23 - Marshmallow 6.0 .

Therefore, setting minSDK 21 for appconfig first required to rewrite DefaultKeyStoreCryptor & SecurityWrapper in order to :

1. Generate RSA pair of keys (using deprecated KeyPairGeneratorSpec API)
2. Generate AES key (using default/other crypto provider)
3. Encrypt the AES key using RSA
4. Store the encrypted AES key in SharedPreferences
5. Manage the different AES key storage/retrieval flow

Then it required anyway additional if-checks in order to prevent KEY_ALIAS null exceptions on some pre-M legacy devices, according to the encryption settings of the device.

**Comment by Enrico204** [comment]
Note that downgrading zxing might [reintroduce some bugs](https://github.com/zxing/zxing/blob/master/CHANGES), and re-implementing `DefaultKeyStoreCryptor` and other classes will require extensive testing.

If supporting older Android versions is necessary, I suggest to duplicate/fork the app and build a "legacy" version, targeting old Android SDKs.

**Comment by rawmain** [comment]
Hello @Enrico204 

> Note that downgrading zxing might [reintroduce some bugs](https://github.com/zxing/zxing/blob/master/CHANGES), and re-implementing `DefaultKeyStoreCryptor` and other classes will require extensive testing.
> 
> If supporting older Android versions is necessary, I suggest to duplicate/fork the app and build a "legacy" version, targeting old Android SDKs.

Honestly, downgrade to minSDK 21 doesn't make sense IMHO too = even re-implementing DefaultKeyStoreCryptor & SecurityWrapper for AES+RSA logic/flow, there will always remain the (known) performance & reliability flaws with API deprecated methods for keystore management on pre-M legacy devices. 

-----------------

Downgrade to minSDK 23 is technically feasible without losing performance & reinstating critical bugs, by working in partial downgrade for Zxing libs (limit core min 3.3.0). 

However, it would require anyway further testing on real devices API 23<->30. 

Until now I haven't got runtime issues with the shared/applied commits, but I'm still in the preliminary testing phase with few (less than 20) real device configs...

-----------------

Therefore, I agree with @astagi = at the present time, **downgrade to minSDK 24 is the only available option, that can be applied in a short time & without critical bugs/issues** - just because of how API desugaring works.

maximum yield less effort in order to extend the app support to API 24 & 25 targets (<6% current working Android shares Italy).


By the rest, we must not forget that VerificaC19 is NOT an app aimed to the widest possible userbase. 

Developers could even spend time to work on a separated legacy build for API 21-22-23... but we are anyway talking about 4% of current Android distribution shares for working devices in Italy (_according to compared stats of Google Play - StatCounter - Statista_).

_"The game is not worth the candle"_ - obviously, still IMHO_

**Comment by astagi** [comment]
Hi @rawmain sorry for my late response, I'm currently on vacation. You did a great work on your PR, very interesting! I let @Light2288 to review your changes but I think at the end they are going to support devices with API >= 24. As you mentioned VerificaC19 app is not aimed to the widest possible userbase.
