### ISSUE TITLE
Front camera?

### ISSUE THREAD

**Issue by AntoBaldo** [ministero-salute/it-dgc-verificaC19-android#96]
Hi, how ca we use front camera? there is a way?

**Comment by EdossProject** [comment]
It also interests me

**Comment by zubeer95** [comment]
The camera is selected in CodeReaderFragment.kt:95 when calling: `binding.barcodeScanner.initializeFromIntent(requireActivity().intent)`

A quick and dirt solution is to write in Firstactivity.tk:164:
` intent.putExtra(Intents.Scan.CAMERA_ID,1);`

Instead of 1 you have to get the camera id of your front camera, there are several ways to do that.

**Comment by EdossProject** [comment]
I use this code:

` private fun openQrCodeReader() {
        val intent = Intent(this, MainActivity::class.java)
        intent.putExtra(Intents.Scan.CAMERA_ID,1);
        startActivity(intent)
    }`

But not work Frontal Camera

**Comment by astagi** [comment]
@EdossProject try the code provided by @zubeer95. 

I'll close this issue cause it's not strictly related to the final app, it will be forced to use back camera for certificates scanning.
